### ISSUE TITLE
Investigate whether "save" must receive a key or not

### ISSUE THREAD

**Issue by rbonifacio** [Angra-DB/core#2]
The key might be a hash map of the time stamp plus something that I don't know yet.

**Comment by ninovasc** [comment]
@rbonifacio After spend some time in this issue I think we could use an auto-generated key concatting `rand:uniform(10000)` and `erlang:system_time(nano_seconds)`. With this method, the risk of collisions is low because we take one in ten thousands chances of collision if the insert where in the same nano second.

Example (http://tryerl.seriyps.ru/#id=57f3):

```
Time=erlang:system_time(nano_seconds),
StringTime=integer_to_list(Time),
UniformRandom=rand:uniform(10000),
StringRandom=integer_to_list(UniformRandom),
Key=StringRandom++StringTime.
```

Using the random number in front of time could be good for the distributions of keys.

This ideia may be enhanced in future making a hash of this key using some library like "hashids" (http://hashids.org/erlang/).

**Comment by rbonifacio** [comment]
I really liked the core idea of the proposed solution. Let's go ahead in that direction, particularly using either hashids or crc32.
